name: Runtime packages
on: 
  push:
    branches:
      - 'bins-extra'
    tags-ignore:
      - v*

jobs:
  containerd:
    name: 'Package: containerd'
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Checkout code into the Go module directory
      uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        sudo bins/autobuild/tf-build-deps.sh

    - name: Build package
      id: package
      run: |
        cd bins
        sudo ./bins-extra.sh --package containerd

    - name: Publish flist (${{ github.sha }})
      if: success()
      uses: threefoldtech/publish-flist@master
      with:
        token: ${{ secrets.HUB_JWT }}
        action: publish
        user: tf-autobuilder
        root: bins/releases/containerd
        name: ${{ steps.package.outputs.name }}.flist
    
