name: Runtime packages
on: 
  push:
    # Matching on any tags which is not a production release
    # Matching:
    #  - v1.0.0-beta5
    #  - v1.0.1-rc3
    #  - v2.1.4-hotfix-87
    #
    # Ignoring:
    #  - v1.0.0
    #  - v1.1.0
    #  - v2.1.13
    tags:
      - 'v*-*'

jobs:
  containerd:
    name: 'Package: containerd'
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Checkout code into the Go module directory
      uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        cd bins
        sudo ./bins-extra.sh --package basesystem

    - name: Build package
      id: package
      run: |
        cd bins
        sudo ./bins-extra.sh --package containerd

    - name: Publish flist (${{ github.sha }})
      if: success()
      uses: threefoldtech/publish-flist@master
      with:
        token: ${{ secrets.HUB_JWT }}
        action: publish
        user: tf-zos-bins.test
        root: bins/releases/containerd
        name: ${{ steps.package.outputs.name }}.flist

  firecracker:
    name: 'Package: firecracker'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        cd bins
        sudo ./bins-extra.sh --package basesystem

    - name: Build package
      id: package
      run: |
        cd bins
        sudo ./bins-extra.sh --package firecracker

    - name: Publish flist (${{ github.sha }})
      if: success()
      uses: threefoldtech/publish-flist@master
      with:
        token: ${{ secrets.HUB_JWT }}
        action: publish
        user: tf-zos-bins.test
        root: bins/releases/firecracker
        name: ${{ steps.package.outputs.name }}.flist
 
  promtail:
    name: 'Package: promtail'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        cd bins
        sudo ./bins-extra.sh --package basesystem

    - name: Build package
      id: package
      run: |
        cd bins
        sudo ./bins-extra.sh --package promtail

    - name: Publish flist (${{ github.sha }})
      if: success()
      uses: threefoldtech/publish-flist@master
      with:
        token: ${{ secrets.HUB_JWT }}
        action: publish
        user: tf-zos-bins.test
        root: bins/releases/promtail
        name: ${{ steps.package.outputs.name }}.flist
 
