name: Publishing Files
on: [push]

jobs:
  build:
    name: Publishing Files
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Checkout code into the Go module directory
      uses: actions/checkout@v1

    - name: Build binaries
      run: |
        cd cmds
        make
      env:
        GO111MODULE: on

    - name: Collecting files
      run: |
        mkdir -p ${{ github.workspace }}/archive/{bin,etc/zinit}
        cp bin/* ${{ github.workspace }}/archive/bin/
        cp -r zinit/* ${{ github.workspace }}/archive/etc/zinit

    - name: Publishing flist
      if: success()
      uses: threefoldtech/publish-flist@master
      with:
        action: publish
        user: tf-autobuilder
        root: archive
        token: ${{ secrets.HUB_JWT }}
        name: zos-${{ github.sha }}.flist

